### ISSUE TITLE
Unable to correctly parse (regex)

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#280] opened 2015-03-16 15:19 UTC
Trying to snatch "Good Witch" ep 1 and 2 which are combined and just named ep 1 pilot, full ignore on the file.

File name available on: the.good.witch.s01e01.720p.hdtv.x264 w4f.mkv
Scene exception added for "The Good Witch" and restarted, it snatched ep 2 from another source but still ignores one so there is a regex issue.

```
2015-03-16 16:15:35 INFO     MANUAL-289855 :: Unable to find a download for: [Good Witch - 1x01 - Starting Over…Again]
2015-03-16 16:15:35 DEBUG    MANUAL-289855 :: formatting pattern: %SN - %Sx%0E - %EN -> Good Witch - 1x01 - Starting Over…Again
2015-03-16 16:15:35 DEBUG    MANUAL-289855 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-03-16 16:15:35 DEBUG    MANUAL-289855 :: formatting pattern: %SN - %Sx%0E - %EN -> Good Witch - 1x01 - Starting Over…Again
2015-03-16 16:15:35 DEBUG    MANUAL-289855 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-03-16 16:15:35 DEBUG    MANUAL-289855 :: [HDTorrents] :: No results found for: The Good Witch S01E01 )
2015-03-16 16:15:34 DEBUG    MANUAL-289855 :: [HDTorrents] :: Search string:
2015-03-16 16:15:34 DEBUG    MANUAL-289855 :: [HDTorrents] :: No results found for: Good Witch S01E01 ()
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [HDTorrents] :: Search string: 
: 
2015-03-16 16:15:28 INFO     MANUAL-289855 :: [HDTorrents] :: Performing episode search for Good Witch
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Unable to parse the filename Shameless.US.S05E09.720p.HDTV.X264-DIMENSION.[无耻家庭(美国版)..第五季第09集] into a valid show
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Using ALL regexes
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Attempting to add item to cache: Shameless.US.S05E09.720p.HDTV.X264-DIMENSION.[无耻家庭(美国版)..第五季第09集]
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Unable to parse the filename The.Good.Wife.S06E15.720p.HDTV.X264-DIMENSION.[傲骨贤妻...第六季第15集] into a valid show
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Using ALL regexes
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Attempting to add item to cache: The.Good.Wife.S06E15.720p.HDTV.X264-DIMENSION.[傲骨贤妻...第六季第15集]
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Unable to parse the filename The.Last.Man.On.Earth.S01E04.720p.HDTV.x264-IMMERSE.[一个人的地球...第一季第04集] into a valid show
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Using ALL regexes
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Attempting to add item to cache: The.Last.Man.On.Earth.S01E04.720p.HDTV.x264-IMMERSE.[一个人的地球...第一季第04集]
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Unable to parse the filename Secrets.and.Lies.US.S01E04.720p.HDTV.x264-KILLERS.[秘密与谎言.第一季第04集] into a valid show
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Using ALL regexes
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Attempting to add item to cache: Secrets.and.Lies.US.S01E04.720p.HDTV.x264-KILLERS.[秘密与谎言.第一季第04集]
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Unable to parse the filename The.Walking.Dead.S05E14.720p.HDTV.x264-KILLERS.[行尸走肉...第五季第14集] into a valid show
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Using ALL regexes
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Attempting to add item to cache: The.Walking.Dead.S05E14.720p.HDTV.x264-KILLERS.[行尸走肉...第五季第14集]
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Unable to parse the filename Looking.S02E09.720p.HDTV.x264-IMMERSE.[寻...第二季第09集] into a valid show
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Using ALL regexes
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Attempting to add item to cache: Looking.S02E09.720p.HDTV.x264-IMMERSE.[寻...第二季第09集]
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Unable to parse the filename Revenge.S04E16.720p.HDTV.X264-DIMENSION.[复仇...第四季第16集] into a valid show
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Using ALL regexes
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Attempting to add item to cache: Revenge.S04E16.720p.HDTV.X264-DIMENSION.[复仇...第四季第16集]
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Unable to parse the filename Battle.Creek.S01E03.720p.HDTV.x264-KILLERS.[江城警事...第一季第03集] into a valid show
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Using ALL regexes
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Attempting to add item to cache: Battle.Creek.S01E03.720p.HDTV.x264-KILLERS.[江城警事...第一季第03集]
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Unable to parse the filename UEFA.Champions.League.2014-15.Highlights.Matchday.8.720p.HDTV.x264-FiHTV.[] into a valid show
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Using ALL regexes
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Attempting to add item to cache: UEFA.Champions.League.2014-15.Highlights.Matchday.8.720p.HDTV.x264-FiHTV.[]
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Unable to parse the filename Brooklyn.Nine-Nine.S02E19.720p.HDTV.x264-IMMERSE[这个警察有点烦/神烦警探/布鲁克林99.第二季第19集] into a valid show
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Using ALL regexes
2015-03-16 16:15:28 DEBUG    MANUAL-289855 :: [TTG] :: Attempting to add item to cache: Brooklyn.Nine-Nine.S02E19.720p.HDTV.x264-IMMERSE[这个警察有点烦/神烦警探/布鲁克林99.第二季第19集]
2015-03-16 16:15:28 WARNING  FEEDCACHE :: Not storing data with exception: document declared as us-ascii, but parsed as utf-8
2015-03-16 16:15:24 DEBUG    MANUAL-289855 :: [TTG] :: TorrentRssCache cache update URL: 
2015-03-16 16:15:24 INFO     MANUAL-289855 :: [TTG] :: Performing episode search for Good Witch
2015-03-16 16:15:24 DEBUG    MANUAL-289855 :: Searching with parameters: {'category': 'Episode', 'tvdb': 289855, 'name': 'S01E01'}
2015-03-16 16:15:24 DEBUG    MANUAL-289855 :: Last update was too soon, using old cache: today()-2015-03-16 16:15:23<0:15:00
2015-03-16 16:15:24 INFO     MANUAL-289855 :: Performing episode search for Good Witch
2015-03-16 16:15:24 INFO     MANUAL-289855 :: FALLBACK EPISODE SEARCH INITIATED ...
2015-03-16 16:15:23 DEBUG    MANUAL-289855 :: [BTN] :: Searching with parameters: {'category': 'Episode', 'tvdb': 289855, 'name': 'S01E01'}
2015-03-16 16:15:23 DEBUG    MANUAL-289855 :: [BTN] :: Unable to parse the filename Comic.Book.Men.S04E14.720p.HDTV.x264-BATV into a valid show
2015-03-16 16:15:23 DEBUG    MANUAL-289855 :: [BTN] :: Using ALL regexes
2015-03-16 16:15:23 DEBUG    MANUAL-289855 :: [BTN] :: Attempting to add item to cache: Comic.Book.Men.S04E14.720p.HDTV.x264-BATV
2015-03-16 16:15:21 DEBUG    MANUAL-289855 :: [BTN] :: Searching with parameters: {'age': '<=931'}
2015-03-16 16:15:21 INFO     MANUAL-289855 :: [BTN] :: Performing season pack search for Good Witch
2015-03-16 16:15:21 DEBUG    MANUAL-289855 :: Internal name cache set to: {u'\u30d5\u30a7\u30a2\u30ea\u30fc\u30c6\u30a4\u30eb': 114801, u'dog with a blog': 263203, u'johnny test': 134991, u'regular show': 188401, u'filthy sexy teens': 274095, u'deadtime stories': 273888, u'stalker': 281697, u'forever 2014': 281535, u'24': 76290, u'jessie': 252312, u'last man standing': 248834, u'davincis demons': 259669, u'falling skies': 205281, u'scorpion': 281630, u'every witch way': 276589, u'suits': 247808, u'brooklyn nine nine': 269586, u'helix': 265912, u'naruto shippuuden': 79824, u'the simpsons': 71663, u'advanced': 76703, u'the goldbergs': 269653, u'the musketeers': 269159, u'2 broke girls': 248741, u'k c undercover': 285824, u'quick draw': 270913, u'girl meets world': 267777, u'give out girls': 286912, u'the rebels': 278292, u'lost girl': 182061, u'mom': 266967, u'liv and maddie': 270423, u'street fighter assassins fist': 281117, u'fairy tail 2': 114801, u'dreamworks dragons riders of berk': 261202, u'once upon a time 2011': 248835, u'cougar town': 94991, u'continuum': 258171, u'over the garden wall': 281643, u'cleaners': 273786, u'the last ship': 33158, u'agents of s h i e l d': 263365, u'indigo league': 76703, u'banshee': 259765, u'da vincis demons': 259669, u'arrow': 257655, u'how to get away with murder': 281620, u'baby daddy': 258602, u'the mccarthys': 281625, u'advanced battle': 76703, u'space dandy 2': 272849, u'archer 2009': 110381, u'castle 2009': 83462, u'from dusk till dawn': 276312, u'penny dreadful': 265766, u'marvels agent carter': 281485, u'bella and the bulldogs': 289585, u'from dusk till dawn the series': 276312, u'all hail king julien': 288926, u'full english': 264071, u'the odd couple 2015': 281700, u'constantine': 38109, u'jessie 2011': 252312, u'the originals': 266883, u'naruto \u75be\u98a8\u4f1d': 79824, u'supernatural': 78901, u'fargo': 269613, u'salem': 274897, u'mr pickles': 277953, u'12 monkeys': 272644, u'perception': 248757, u'resurrection us': 269650, u'the johto journeys': 76703, u'marry me 2014': 281589, u'deadbeat': 279392, u'the flash 2014': 279121, u'galavant': 281619, u'star vs the forces of evil': 282994, u'dig': 275278, u'defiance': 255326, u'resurrection': 269650, u'the thundermans': 274283, u'pretty little liars': 146711, u'black and white': 76703, u'adventure time with finn and jake': 152831, u'the millers': 269644, u'master quest': 76703, u'steven universe': 270701, u'the librarians 2014': 281709, u'the awesomes': 268914, u'bojack horseman': 282254, u'the venture bros': 72306, u'dominion': 277462, u'diamond and pearl': 76703, u'the 100': 268592, u'castle': 83462, u'legends 2014': 265074, u'black and white rival destinies': 76703, u'mother up': 275048, u'the strain': 276564, u'south park': 75897, u'hollands hoop': 45688, u'gravity falls': 259972, u'advanced challenge': 76703, u'sense8': 268156, u'black and white adventures in unova': 76703, u'the exes': 253279, u'xy': 76703, u'lab rats 2012': 256394, u'elementary': 255316, u'pokemon': 76703, u'bitten': 269550, u'grimm': 248736, u'diamond and pearl battle dimension': 76703, u'yonderland': 270668, u'new girl': 248682, u'the mentalist': 82459, u'dragons riders of berk': 261202, u'black dynamite': 250821, u'brickleberry': 259569, u'marvels agents of s h i e l d': 263365, u'one big happy': 281590, u'the venture brothers': 72306, u'atlantis': 248596, u'american dad': 73141, u'forever': 281535, u'my little pony friendship is magic': 212171, u'sirens 2014': 269897, u'star wars rebels': 283468, u'diamond and pearl sinnoh league victors': 76703, u'sleepy hollow': 269578, u'doctor who 2009': 112671, u'dragons defenders of berk': 261202, u'doctor who 2005': 78804, u'haven': 158661, u'last man standing us': 248834, u'naruto shippuden': 79824, u'hemlock grove': 259948, u'richie rich 2015': 292506, u'i didnt do it': 270849, u'forever us': 281535, u'archer': 110381, u'fairy tail s2': 114801, u'tbbt': 80379, u'fairy tail 2014': 114801, u'the librarians us': 281709, u'teen wolf': 175001, u'beauty and the beast 2012': 258959, u'phineas and ferb': 81848, u'from dusk til dawn': 276312, u'dragons': 261202, u'spooksville': 274738, u'family guy': 75978, u'big bang theory': 80379, u'sherlock': 176941, u'bones': 75682, u'izombie': 281470, u'supah ninjas': 220991, u'melissa and joey': 168621, u'adventures on the orange islands': 76703, u'max and shred': 286828, u'hot in cleveland': 162071, u'marvels daredevil': 281662, u'rick and morty': 275274, u'i didnt do it 2014': 270849, u'awkward': 249882, u'under the dome': 264492, u'once upon a time': 248835, u'gotham': 274431, u'atlantis 2013': 248596, u'powers 2015': 286943, u'wizards vs aliens': 262513, u'unbreakable kimmy schmidt': 281593, u'space dandy': 272849, u'undateable 2014': 269618, u'fairy tail': 114801, u'good witch': 289855, u'the good witch': 289855, u'the big bang theory': 80379, u'young dracula': 80248, u'faking it 2014': 277169, u'two and a half men': 72227, u'battle frontier': 76703, u'the blacklist': 266189, u'silicon valley': 277165, u'vincis demons': 259669, u'johto league champions': 76703, u'last man standing 2011': 248834, u'lab rats': 256394, u'the vampire diaries': 95491, u'pok\xe9mon': 76703, u'mike tyson mysteries': 277954, u'person of interest': 248742, u'wayward pines': 269750, u'extant': 272127, u'adventure time': 152831, u'the goldbergs 2013': 269653, u'marvel agents of shield': 263365, u'young and hungry': 277021, u'the wrong mans': 268943, u'diamond and pearl galactic battles': 76703}
2015-03-16 16:15:21 INFO     MANUAL-289855 :: Building internal name cache for Good Witch
2015-03-16 16:15:21 INFO     MANUAL-289855 :: No scene exceptions update needed
2015-03-16 16:15:21 DEBUG    MANUAL-289855 :: Transaction with 0 queries executed
2015-03-16 16:15:21 INFO     MANUAL-289855 :: Beginning manual search for: [Good Witch - 1x01 - Starting Over…Again]
2015-03-16 16:15:21 DEBUG    MANUAL-289855 :: formatting pattern: %SN - %Sx%0E - %EN -> Good Witch - 1x01 - Starting Over…Again
2015-03-16 16:15:21 DEBUG    MANUAL-289855 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
```

**Comment by JackDandy** [comment] 2015-03-17 01:10
Same thing happens with powers 2015. At this point, I just go in and manually changed selected episodes to "downloaded" for ep 2 and everything else was fine after that.

I'm marking this issue as "wont fix" because this issue is caused by bad filenaming at source. The source file should be named something like showname.s01e01-e02 otherwise there is no way for SG to make the distinction of ep 2.

**Closed by JackDandy** 2015-03-17 01:10 UTC

**Comment by Th3MadHatter** [comment] 2015-03-17 10:29
Yeah but the problem with this one is that it DOESN'T pick it up as episode 1 which it is named as, so I was able to drag episode 2 and 3 from another source but ep 1 is ignored all together.
Normally there are no problems with ep 1 and 2 or whatever in 1 episode, sometimes it fucks up the naming a bit but nothing bad really, this time it totally ignores all the files available.

**Comment by JackDandy** [comment] 2015-03-17 11:31
i have just created a file with the name you supplied, then i did the pp and my result is success...
```
Parsed good.witch.s01e01.720p.hdtv.x264 w4f
.. into good witch - S1E1 [ABD: False] [ANIME: False] [whichReg: ['standard']]
Retrieving episode object for 1x1
Using "HD TV" quality from the snatch history
Existing episode status is not downloaded/archived, marking it safe to replace
No release found in snatch history
Destination folder for this episode is V:\VideoDraft\tv_draft\Good Witch\Season 01
Moved file from V:\_incoming\_files\_sb pp\New folder\good.witch.s01e01.720p.hdtv.x264 w4f.mkv
.. to V:\VideoDraft\tv_draft\Good Witch\Season 01\Good.Witch.s01e01.Starting.Over…Again.HD.TV-SickGear.mkv
Successfully processed good.witch.s01e01.720p.hdtv.x264 w4f.mkv
-----------------------
Successfully processed.
```

**Comment by Th3MadHatter** [comment] 2015-03-17 13:24
Then why the hell does it ignore it on my end -_-' I have the exact same file with the exact same name but I get a "No files found".
