### ISSUE TITLE
"Exception generated in thread POSTPROCESSER"

### ISSUE THREAD

**Issue by sverr1** [SickGear/SickGear#164] opened 2015-01-28 12:51 UTC
So, I've been having these issues sometimes where SG isn't post processing properly.

It snatches fine. Renames and moves the file, but doesn't create the .nfo or -thumb.jpg file. Still marks it as downloaded in the series overview but doesn't report it as downloaded in history.

http://pastebin.com/NPPtfHdW for the logfile

![image](https://cloud.githubusercontent.com/assets/10365546/5937806/7f9412e4-a6f4-11e4-8d63-39f0491c8e86.png)

![image](https://cloud.githubusercontent.com/assets/10365546/5937814/9512faa4-a6f4-11e4-83f1-904570d3a8f0.png)

It's also worth noting that if I ask SG to re-scan the series with the issue, it creates the .nfo and -thumb.jpg file just fine.

**Comment by JackDandy** [comment] 2015-02-02 19:19
A nice report. However, we can't reproduce the issue; it appears to be local to that install. For this reason, this issue is closed as 'invalid'.

**Closed by JackDandy** 2015-02-02 19:19 UTC
Labels: Invalid
