### ISSUE TITLE
Kickasstorrents ?

### ISSUE THREAD

**Issue by sendas** [SickGear/SickGear#378] opened 2015-06-02 18:07 UTC
Hi

When I check the logs, I can see this: 

2015-06-02 18:48:01 WARNING  PROPER-SEARCH :: [KickAssTorrents] :: Connection error ('Connection aborted.', gaierror(-5, 'No address associated with hostname')) while loading URL http://www.kickmirror.com/usearch/Devious.Maids%20S03E01%7C3x01%20PROPER%7CREPACK%20category%3Atv/?field=seeders&sorder=desc

The links is dead... It's not using the correct mirror site...

Thanks

Version:	BRANCH: (master) / COMMIT: (24b2938c9c45cb34285687a1d7d52bd90936cd5d) 
This is BETA software.
Config file:	/home/pi/.sickgear/config.ini
Database file:	/home/pi/.sickgear/sickbeard.db
Cache Dir:	/home/pi/.sickgear/cache
Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickbeard.pid', '--datadir=/home/pi/.sickgear/']
Web Root:	
Python Version:	2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]

**Comment by JackDandy** [comment] 2015-06-03 16:32
"The links is dead... It's not using the correct mirror site..."

And what is the "correct mirror" that you mention ?

**Comment by sendas** [comment] 2015-06-03 16:41
this one?

https://kat.cr/

**Comment by JackDandy** [comment] 2015-06-03 16:46
No, that isn't a new mirror. The existing mirror is not a wrong URL, it has simply been taken offline. I am currently changing this code anyway, but these changes will not reach master branch for a few weeks. Until then, disable this provider.

**Comment by sendas** [comment] 2015-06-03 16:52
But most of my downloads came from there... Sometimes works, sometimes it doesnt'... 

![captura de ecra 2015-06-3 as 17 51 03](https://cloud.githubusercontent.com/assets/10220908/7966014/2c93ab6c-0a19-11e5-9438-d87657875189.png)

**Comment by JackDandy** [comment] 2015-06-03 16:56
Where it has failed, go into the displayShow of that episode and hit the manual search button on the right to trigger a new snatch, basic user stuff that will last you until the issue is fixed on master.

**Comment by sendas** [comment] 2015-06-03 16:57
That's what I've been doing :) thanks !

**Closed** 2015-06-03 16:58 UTC
Labels: Needs More Info
