### ISSUE TITLE
Copies of same quality are being replaced when a higher quality snatch fails.

### ISSUE THREAD

**Issue by mrowlinson** [SickGear/SickGear#902] opened 2017-02-02 15:43 UTC
1. BRANCH: master / COMMIT: bc7b6ff2dc8a460047011863fc17714e0d87e8b5
2. 
- **What should happen:** When a download of a higher copy fails it should look for another higher quality copy or quit until new copies are located.
- **What actually happens:** The higher quality copy fails and no other higher quality copies are found so it redownloads the existing copy.
3. This seems to happen any time I have a show with a 720p BluRay copy in my library and 1080p BluRay is the desired best quality and all the 1080p downloads available fail.
4. Here is the text from the nzbtoMedia script, and below that are the only things I can find in the log which would seem to be relevant:

**[edit: log removed] thanks**

**Comment by JackDandy** [comment] 2017-02-04 10:51
This is a deep and complex issue coming from how the failed download handler was designed. For now it is advised to have only one of the features FDH or show upgrades enabled at the same time. To be clear, either disable all show updates to bluray level, or disable Failed Download Handling.

**Comment by mrowlinson** [comment] 2017-02-04 17:44
I guess I'll disabled failed download handling because I'm more concerned about having the highest quality copy available. 

I honestly wouldn't mind so much about it redownloading the 720p blurays (I've got a 750/750 connection so they download almost instantly) except for that the fact that sometimes the copies it downloads are lower quality copies than the ones I already had. Is it possible, as a quick temporary fix, to create an option for the media parser to never replace larger file size with a smaller one unless specifically told to do so by the user? Then I could keep failed downloading turned on and if the 720p copy it redownloaded was a lower quality it wouldn't be allowed to replace it and I could just go through and delete those manually when I see it happen.

**Comment by JackDandy** [comment] 2017-02-04 17:54
@Prinz23 .. you have way better knowledge on this and I appreciate there will be issues even on this idea... your thoughts...

**Comment by qorron** [comment] 2017-02-06 17:27
instead of having a separate states for file state (absent, present with quality xy, ..) and search state (satisfied, snatched with quality xy, open) the state of an episode is stored in one field. there is a rather complicated way of backing up the state and restoring it once a download fails but that does not cover all possible cases.
of course it is not enough to slap an additional field onto that and be done with it. fixing this is not easy.

**Comment by fernandog** [comment] 2017-02-06 17:45
@JackDandy if you allow me to reply, SickGear revert previous status

https://github.com/SickGear/SickGear/blob/master/sickbeard/failed_history.py#L115-L133

So if you had a 720p HDTV snatch&PP ok but now snatched a failed 720 Bluray, FDH will revert episode to "Downloaded 720p HDTV" (also keep 720p HDTV file) and keep looking for another 720p Bluray.

At least is how it supposed to work

**Comment by JackDandy** [comment] 2017-02-13 16:41
@mrowlinson please come to irc if you wanna test a fix for this. closing issue now.

**Closed by JackDandy** 2017-02-13 16:41 UTC

**Comment by mrowlinson** [comment] 2017-04-16 23:21
This issue is still occurring. I just updated a bunch of shows to 1080p Bluray as the highest desired quality, from 720p Bluray, and after the backlog search it's doing the same thing again. When all of the 1080p copies are downloaded and fail it then tries to redownload the existing copy. This time it replaced some existing 720p bluray copies with lower quality copies and the higher quality copies are no longer available so I'm stuck with inferior quality episodes.

**Comment by JackDandy** [comment] 2017-04-18 14:52
Can you confirm that shows snatched were snatched AFTER enabling FDH. Perhaps the fails are with shows from before the option was enabled.

**Comment by mrowlinson** [comment] 2017-04-18 15:08
I never actually disabled failed download handling despite saying above that I would, so yes they were definitely snatched while FDH was enabled.

**Comment by mrowlinson** [comment] 2017-04-27 20:52
Are there any updates on this? This keeps happening.

**Comment by JackDandy** [comment] 2017-04-27 21:25
"For now it is advised to have only one of the features FDH or show upgrades enabled at the same time. To be clear, either disable all show updates to bluray level, or disable Failed Download Handling."

The issue is on todo, i looked at it two months ago, given you did not reply at that time the issue was put to bed, therefore, something new must now be causing this given it is assumed you tested the fix already submitted back then. There is no eta to look at this atm.
