### ISSUE TITLE
subtitle-ish errors 

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#256] opened 2015-03-09 22:49 UTC
Lots of subtitle-ish errors going on.

It happens at random or when forcing PP.

BRANCH: (develop) / COMMIT: (e9251b3e477712a1d2be8ddb8371865f1d243e81)
This is BETA software.
OS: Windows
How to reproduce, pick a file, ive it a go
```
2015-03-09 23:32:26 TORNADO :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "C:\SickGear\sickbeard\tv.py", line 1407, in downloadSubtitles
    multi=True, cache_dir=sickbeard.CACHE_DIR)
  File "C:\SickGear\lib\subliminal\api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\SickGear\lib\subliminal\api.py", line 54, in list_subtitles
    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\SickGear\lib\subliminal\core.py", line 57, in create_list_tasks
    scan_result.extend(scan(p, max_depth, scan_filter))
  File "C:\SickGear\lib\subliminal\videos.py", line 246, in scan
    video = Video.from_path(entry)
  File "C:\SickGear\lib\subliminal\videos.py", line 85, in from_path
    result = Episode(path, guess['series'], guess['season'], guess['episodeNumber'], title, guess)
  File "C:\SickGear\lib\subliminal\videos.py", line 187, in __init__
    super(Episode, self).__init__(path, guess, imdbid)
  File "C:\SickGear\lib\subliminal\videos.py", line 68, in __init__
    self._compute_hashes()
  File "C:\SickGear\lib\subliminal\videos.py", line 119, in _compute_hashes
    self.hashes['OpenSubtitles'] = hash_opensubtitles(self.path)
  File "C:\SickGear\lib\subliminal\videos.py", line 262, in hash_opensubtitles
    with open(path, 'rb') as f:
IOError: [Errno 22] invalid mode ('rb') or filename: 'G:\\videos\\tv\\The Goldbergs (2013)\\The Goldbergs (2013) - S02E13 - Van People.mkv'

2015-03-09 23:31:50 TORNADO :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "C:\SickGear\sickbeard\tv.py", line 1407, in downloadSubtitles
    multi=True, cache_dir=sickbeard.CACHE_DIR)
  File "C:\SickGear\lib\subliminal\api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\SickGear\lib\subliminal\api.py", line 54, in list_subtitles
    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\SickGear\lib\subliminal\core.py", line 57, in create_list_tasks
    scan_result.extend(scan(p, max_depth, scan_filter))
  File "C:\SickGear\lib\subliminal\videos.py", line 246, in scan
    video = Video.from_path(entry)
  File "C:\SickGear\lib\subliminal\videos.py", line 85, in from_path
    result = Episode(path, guess['series'], guess['season'], guess['episodeNumber'], title, guess)
  File "C:\SickGear\lib\subliminal\videos.py", line 187, in __init__
    super(Episode, self).__init__(path, guess, imdbid)
  File "C:\SickGear\lib\subliminal\videos.py", line 68, in __init__
    self._compute_hashes()
  File "C:\SickGear\lib\subliminal\videos.py", line 119, in _compute_hashes
    self.hashes['OpenSubtitles'] = hash_opensubtitles(self.path)
  File "C:\SickGear\lib\subliminal\videos.py", line 262, in hash_opensubtitles
    with open(path, 'rb') as f:
IOError: [Errno 22] invalid mode ('rb') or filename: 'G:\\videos\\tv\\The Blacklist\\The Blacklist - S02E14 - T. Earl King VI.mkv'

2015-03-09 23:31:02 TORNADO :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "C:\SickGear\sickbeard\tv.py", line 1407, in downloadSubtitles
    multi=True, cache_dir=sickbeard.CACHE_DIR)
  File "C:\SickGear\lib\subliminal\api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\SickGear\lib\subliminal\api.py", line 54, in list_subtitles
    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\SickGear\lib\subliminal\core.py", line 57, in create_list_tasks
    scan_result.extend(scan(p, max_depth, scan_filter))
  File "C:\SickGear\lib\subliminal\videos.py", line 246, in scan
    video = Video.from_path(entry)
  File "C:\SickGear\lib\subliminal\videos.py", line 85, in from_path
    result = Episode(path, guess['series'], guess['season'], guess['episodeNumber'], title, guess)
  File "C:\SickGear\lib\subliminal\videos.py", line 187, in __init__
    super(Episode, self).__init__(path, guess, imdbid)
  File "C:\SickGear\lib\subliminal\videos.py", line 68, in __init__
    self._compute_hashes()
  File "C:\SickGear\lib\subliminal\videos.py", line 119, in _compute_hashes
    self.hashes['OpenSubtitles'] = hash_opensubtitles(self.path)
  File "C:\SickGear\lib\subliminal\videos.py", line 262, in hash_opensubtitles
    with open(path, 'rb') as f:
IOError: [Errno 22] invalid mode ('rb') or filename: 'G:\\videos\\tv\\The Big Bang Theory\\The Big Bang Theory - S08E17 - The Colonization Application.mkv'
```

**Comment by JackDandy** [comment] 2016-02-10 09:09
It has been proposed to remove subtitle support completely because there is no real demand for it in sg and specialist tools exist for the task.

**Comment by JackDandy** [comment] 2016-02-27 08:24
There's been feedback that this feature does work, therefore, I'm closing this issue and marking invalid as there was no other information to help reproduce and there is clearly something specific missing from this report that is causing this. Perhaps it was the way the files were named on the system that couldn't be matched, I dunno.

**Closed by JackDandy** 2016-02-27 08:24 UTC
Labels: Invalid

**Comment by Fire69** [comment] 2018-05-17 08:06
Hey,

Did a full reinstall of my server and SickGear this weekend and I'm having the same errors as Th3MadHatter
I didn't use the subtitles plugin before so I don't know if the problem is new or now :)

`2018-05-16 02:22:57 FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/home/sickgear/SickGear/sickbeard/tv.py", line 1696, in downloadSubtitles
    multi=True, cache_dir=sickbeard.CACHE_DIR)
  File "/home/sickgear/SickGear/lib/subliminal/api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/home/sickgear/SickGear/lib/subliminal/api.py", line 62, in list_subtitles
    service_instance.terminate()
  File "/home/sickgear/SickGear/lib/subliminal/services/opensubtitles.py", line 103, in terminate
    raise ServiceError(str(e))
ServiceError`

No worries if you're planning on discontinuing subtitles altogether.
Just wanted to let you know that it's not a single case :-)

**Comment by JackDandy** [comment] 2018-05-17 09:40
> Just wanted to let you know that it's not a single case :-)

Hello @Fire69 

I did not disbelieve the issue, which is what you are adding to this thread with that comment, what would be far more useful is the detail as is asked for in the following link! 

Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

It's very simple, if you can describe how to replicate, then there is a chance for the issue to be looked at. Normally, subs are working, though an error case was fixed a few months ago.

Thank you.

**Comment by Fire69** [comment] 2018-05-17 11:08
I don't see how you get that's what implying to be honest...
Just wanted to point out that since nobody else commented on the issue that it wasn't only related to his install.

So, here some extra info:
1. State branch and current commit hash from "About" (old:"Help & Info page") (OS helps too)
Ubuntu 18.04 Server / BRANCH: develop / COMMIT: 531491f30c2b5cbb552338150bf1f08ce2e92556

2. Explain what you expect to see and what you actually see (less than 250 chars for each)
I expected to see nothing but got the mentioned errors instead ;-)

3. Reproduce the issue again yourself and clearly write the steps taken
To reproduce it, I enabled the subtitles search and selected any of the plugins
Opened Missing Subtitles management and searched for all missing subtitles.

4. Include relevant logs (see note4 and image), screenshots and configuration information
When changing the loglevel, there's actually 2 different errors, but one is caused by Opensubtitles (too many requests)
<pre>
2018-05-17 12:53:36 ERROR    SUBLIMINAL :: Error consuming task ListTask(Episode(/mnt/datadisk/data/Videos/Series/The 100/Season 04/The 100 - 04x03 - The Four Horsemen.mkv), language_set([Language(Dutch; Flemish)]), opensubtitles, ServiceConfig(True, /home/sickgear/SickGear/cache))
 1) Traceback (most recent call last):
 2)   File "/home/sickgear/SickGear/lib/subliminal/api.py", line 57, in list_subtitles
 3)     result = consume_task(task, service_instances)
 4)   File "/home/sickgear/SickGear/lib/subliminal/core.py", line 130, in consume_task
 5)     service = get_service(services, task.service, config=task.config)
 6)   File "/home/sickgear/SickGear/lib/subliminal/core.py", line 207, in get_service
 7)     services[service_name].init()
 8)   File "/home/sickgear/SickGear/lib/subliminal/services/opensubtitles.py", line 92, in init
 9)     result = self.server.LogIn('', '', 'eng', self.user_agent)
10)   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
11)     return self.__send(self.__name, args)
12)   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
13)     verbose=self.__verbose
14)   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
15)     return self.single_request(host, handler, request_body, verbose)
16)   File "/usr/lib/python2.7/xmlrpclib.py", line 1331, in single_request
17)     response.msg,
18) ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 429 Too Many Requests>
</pre>

The other one is the error from the startpost.
<pre>
2018-05-17 12:53:36 ERROR    TORNADO :: Error occurred when downloading subtitles: Traceback (most recent call last):
 1)   File "/home/sickgear/SickGear/sickbeard/tv.py", line 1696, in downloadSubtitles
 2)     multi=True, cache_dir=sickbeard.CACHE_DIR)
 3)   File "/home/sickgear/SickGear/lib/subliminal/api.py", line 95, in download_subtitles
 4)     subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
 5)   File "/home/sickgear/SickGear/lib/subliminal/api.py", line 62, in list_subtitles
 6)     service_instance.terminate()
 7)   File "/home/sickgear/SickGear/lib/subliminal/services/opensubtitles.py", line 103, in terminate
 8)     raise ServiceError(str(e))
 9) ServiceError
</pre>

**Comment by Fire69** [comment] 2018-05-17 11:26
OK, after noticing there are actually 2 different errors I did some more testing.
And it seems like one error is caused by the other.
I only get the errors when Opensubtitles is selected.  So it's all probably just related to the 'Too many requests'.

**Comment by JackDandy** [comment] 2018-05-17 11:31
I added a the show 100 and processed a file "The.100.s04e03.The.Four.Horsemen.HD.TV.mkv"

so that it would be ready for the steps you provided.

When I follow your steps, and enable opensubtitles I get "All of your episodes have All subtitles".

There is something I am missing on how to recreate this issue.

**Comment by Fire69** [comment] 2018-05-17 11:36
Isn't that probably because you only searched for 1 ep which wouldn't cause the 'too many requests'?

**Comment by JackDandy** [comment] 2018-05-17 11:46
I have no idea. That's why steps are requested,  so that we don't waste time trying to find out how to replicate something that is happening on some system.

**Comment by JackDandy** [comment] 2018-05-17 15:02
> I'm no coder, so I'm doing the best I can here ;-)  

The joke i have to say here, is a movie called "See no evil, Hear no evil" - or the expression, the blind leading the blind,...

The reason i say that is you are not a coder, i am, but i know nearly nothing about the subtitles as i don't use them and well you know my previous thoughts about wanting to deprecate them entirely, so, you are literally leading me too :-)

Sooo, you say you made SG search for 1, and then for all, as you can control SG to do 1, then can you test with 10, and then if not the desired result, test with 20, 40 until you get that sweet spot. And *then*, and here is the most important detail, tell me how you selected 20 or 40, as i have no idea how to actually do that, lol.

**Comment by Fire69** [comment] 2018-05-17 15:14
LOL :-P

Quite basic actually how I did to select 1 or everything.  I just went here:
![image](https://user-images.githubusercontent.com/1757287/40186248-ea8cfdf2-59f4-11e8-82ce-cddb32d78c42.png)
Then I either selected a show with just 1 missing subtitles or I selected all shows. :-)

Instead of testing with 10, 20, 40, ... I didn't resist the lazy approach and first did a quick google :-P
Look what I found: https://forum.opensubtitles.org/viewtopic.php?t=16072
That will probably be more helpful than my testing :-)

**Comment by JackDandy** [comment] 2018-05-17 15:26
That is interesting detail, and given there has been no change to the subbie code, then there most certainly will not be any rate limiting logic in effect, so I will need to investigate deeper now, thanks for the research and guidance :)

**Comment by Fire69** [comment] 2018-05-17 15:30
No, thank YOU for putting your time into it AND for SG in general, couldn't live without it anymore! 😃 👍 🍺
