### ISSUE TITLE
[FR] ability to add TV show containing no season/episode data at indexer

### ISSUE THREAD

**Issue by sweatherlyuk** [SickGear/SickGear#499] opened 2015-09-02 18:03 UTC
Applies to: master release/0.10.0 (1e6c1618871f8cb5781d35114f21d249c270245f)

Issue: Adding a TV show that the TV indexers know but contain no season/episode data for results in an error (applies to both theTVDB and TVRage).

Reproduce steps:
	1. Add a show that the TV indexers know but don't yet contain season/episode data for (currently the show "DC's Legends of Tomorrow" is such a show)

Log (I have removed the apikey in the log below in case this contained sensitive data):
<pre>
2015-09-02 00:34:48 SHOWQUEUE-ADD :: Show DC's Legends of Tomorrow is on theTVDB but contains no season/episode data.
2015-09-02 18:50:07 ERROR    SHOWQUEUE-ADD :: Show DC's Legends of Tomorrow is on theTVDB but contains no season/episode data.
2015-09-02 18:50:07 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'xxxxxxxxxxxx', 'cache': '.sickgear/cache/indexers/theTVDB', 'language': 'en'}
2015-09-02 18:50:07 INFO     SHOWQUEUE-ADD :: Starting to add show /media/WD80GB/Sickbeard/DC's Legends of Tomorrow
</pre>

Additional notes:
I would expect the show to be added to my list of shows (as it is in Sickbeard, see screenshot below). With the current behaviour I would have to remember to add it again at a later date, whereas in Sickbeard it is added and once the episodes are known to the TV indexer Sickbeard updates with the episode data without any manual intervention.

![sickbeard future show](https://cloud.githubusercontent.com/assets/14097198/9646350/a6f7ccb4-51ca-11e5-99ed-79c1ca0ec6da.png)

**Comment by sweatherlyuk** [comment] 2015-09-02 18:38
Searching the issues list something similar was raised previously and fixed:
https://github.com/SickGear/SickGear/issues/43

I wonder if this has been reintroduced?

**Comment by adam111316** [comment] 2015-09-03 09:17
@JackDandy I'll leave this one with you as I remember you made a fix for this ages ago. (I haven't tested the validity of the bug yet)

**Comment by adam111316** [comment] 2015-09-03 09:19
Also note it applies to master, so up to you if you want to hotfix if there is a patch

**Comment by JackDandy** [comment] 2015-09-06 17:58
Regardless of the past, this feature was changed so that adding a show with no show data is currently handled and a popup is presented to the user that the show cannot be added - it is the presence of this handler that i call this a feature request and not a bug. This [FR] is currently in development and is being tested. So it will be merged at some point.

**Comment by sweatherlyuk** [comment] 2015-09-08 21:31
Appreciate the update JackDandy, and great to hear this is currently in development.

**Comment by JackDandy** [comment] 2015-10-16 22:57
#538

**Closed by JackDandy** 2015-10-16 22:57 UTC
Labels: Enhancement
