### ISSUE TITLE
Sickgear postprocessor causes Kodi library corruption with certain nonstandard named files

### ISSUE THREAD

**Issue by dirkblaster** [SickGear/SickGear#854] opened 2017-01-05 12:27 UTC
# Branch: master / COMMIT: 89efdc6f75c613ee9cdfaf9cc49a5853c908796a

Expectation | Result
------------ | -------------
Sickgear postprocessor updates filenames and sends update library request to Kodi | Sickgear has automatically snatched some files with the below structure which has caused a strange update string to be sent, Kodi v16.1 now endlessly create multiple copies of the same episode and I am now working to salvage the database. The postprocessor was able to successfully rename the file and shift it to the correct location, so I'm unsure what exactly has been broken, looking purely at the downloaded and processed files. 

**Steps to reproduce:**
*1)* In this example, the file in question appears to be Marvels.Agents.of.S.H.I.E.L.D.S03E15.480p.177mb.Proper.HDTV.x264-][ Spacetime ][ 06-Apr-2016 ].mp4
*2)* After post processing, Kodi will end up with between 2-12 copies of all episodes within a particular season. This also appears to have affected other shows/seasons randomly
*3)* Clean library does not appear to work, and removing Kodi's TV Show drive source and reimporting the entire drive does not appear to have fixed the issue, there has been some sort of internal damage to the database I am still working to resolve
*4)* Note: I am unable to reproduce the issue as all library update operations are currently taking 30+ minutes due to these phantom episodes now appearing throughout, even though they all appear to point at the same file within Kodi, which is causing the host PC to crash

Note near the bottom, there is an interesting oddity where the log reads:
<pre>
2017-01-04 00:03:48 DEBUG    POSTPROCESSER :: Kodi: Updating Marvel's Agents of S.H.I.E.L.D. on localhost:8080 at G:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[etc]
</pre>

<pre>
2017-01-04 00:03:43 INFO     POSTPROCESSER :: Processing... Marvels.Agents.of.S.H.I.E.L.D.S03E15.480p.177mb.Proper.HDTV.x264-][ Spacetime ][ 06-Apr-2016 ].mp4
2017-01-04 00:03:43 DB       POSTPROCESSER :: sickbeard.db: SELECT * FROM history WHERE resource LIKE ? with args [u'Downloads']
2017-01-04 00:03:43 INFO     POSTPROCESSER :: Analyzing name None
2017-01-04 00:03:43 INFO     POSTPROCESSER :: Analyzing name u'Marvels.Agents.of.S.H.I.E.L.D.S03E15.480p.177mb.Proper.HDTV.x264-][ Spacetime ][ 06-Apr-2016 ].mp4'
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Using ALL regexes
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Parsed Marvels.Agents.of.S.H.I.E.L.D.S03E15.480p.177mb.Proper.HDTV.x264-][ Spacetime ][ 06-Apr-2016 ].mp4 into Marvels Agents of S H I E L D - S3E15 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Parsed Marvels Agents of S H I E L D - S3E15 [ABD: False] [ANIME: False] [whichReg: ['standard']] from Marvels.Agents.of.S.H.I.E.L.D.S03E15.480p.177mb.Proper.HDTV.x264-][ Spacetime ][ 06-Apr-2016 ].mp4
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Parse result not sufficient (all following have to be set). will not save release name
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Parse result(series_name): Marvels Agents of S H I E L D
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Parse result(season_number): 3
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Parse result(episode_numbers): [15]
2017-01-04 00:03:43 DEBUG    POSTPROCESSER ::  or Parse result(air_date): None
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Parse result(release_group): None
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Retrieving episode object for 3x15
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Using "SD TV" quality from the snatch history
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Proper or repack with same quality, marking it safe to replace
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Deleted file G:\Marvel's Agents of S.H.I.E.L.D\Marvel's Agents of S.H.I.E.L.D - S03E15 - Spacetime.mp4
2017-01-04 00:03:43 INFO     POSTPROCESSER :: Trying to clean any empty folders under G:\Marvel's Agents of S.H.I.E.L.D
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: 263365: Not creating SQL queue - record is not dirty
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Using ALL regexes
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Unable to parse the filename Downloads into a valid show
2017-01-04 00:03:43 WARNING  POSTPROCESSER :: No snatched release found in history
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Episode has no release name, replacing it with a generic one: %SN - S%0SE%0E - %EN
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: formatting pattern: %SN - S%0SE%0E - %EN -> Marvel's Agents of S.H.I.E.L.D - S03E15 - Spacetime
2017-01-04 00:03:43 DEBUG    POSTPROCESSER :: Destination folder for this episode is G:\Marvel's Agents of S.H.I.E.L.D
2017-01-04 00:03:47 DEBUG    POSTPROCESSER :: Copied file from E:\Downloads\Marvels.Agents.of.S.H.I.E.L.D.S03E15.480p.177mb.Proper.HDTV.x264-][ Spacetime ][ 06-Apr-2016 ].mp4 to G:\Marvel's Agents of S.H.I.E.L.D\Marvel's Agents of S.H.I.E.L.D - S03E15 - Spacetime.mp4
2017-01-04 00:03:47 DEBUG    POSTPROCESSER :: Setter sets location to G:\Marvel's Agents of S.H.I.E.L.D\Marvel's Agents of S.H.I.E.L.D - S03E15 - Spacetime.mp4
2017-01-04 00:03:47 DEBUG    POSTPROCESSER :: 263365: Not creating SQL queue - record is not dirty
2017-01-04 00:03:47 DB       POSTPROCESSER :: sickbeard.db: INSERT INTO history (action, date, showid, season, episode, quality, resource, provider, version) VALUES (?,?,?,?,?,?,?,?,?) with args [104, '20170104000347', 263365, 3, 15, 1, u'E:\\Downloads\\Marvels.Agents.of.S.H.I.E.L.D.S03E15.480p.177mb.Proper.HDTV.x264-][ Spacetime ][ 06-Apr-2016 ].mp4', -1, -1]
2017-01-04 00:03:47 DEBUG    POSTPROCESSER :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN - %QN
2017-01-04 00:03:47 DEBUG    POSTPROCESSER :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Marvel's Agents of S.H.I.E.L.D - 3x15 - Spacetime - SD TV
2017-01-04 00:03:47 DEBUG    POSTPROCESSER :: Notification for NMJ scan update not enabled, skipping this notification
2017-01-04 00:03:48 DEBUG    POSTPROCESSER :: Kodi: Sending request to update library for host: "localhost:8080"
2017-01-04 00:03:48 DEBUG    POSTPROCESSER :: Kodi: JSON library update. Host: localhost:8080 Show: Marvel's Agents of S.H.I.E.L.D.
2017-01-04 00:03:48 DEBUG    POSTPROCESSER :: Kodi: Updating Marvel's Agents of S.H.I.E.L.D. on localhost:8080 at G:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\Marvel's Agents of S.H.I.E.L.D\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
2017-01-04 00:03:48 WARNING  POSTPROCESSER :: Kodi: Success: profile;"Master user" at host;localhost:8080 updated for show;"Marvel's Agents of S.H.I.E.L.D."
2017-01-04 00:03:48 INFO     POSTPROCESSER :: Successfully processed Marvels.Agents.of.S.H.I.E.L.D.S03E15.480p.177mb.Proper.HDTV.x264-][ Spacetime ][ 06-Apr-2016 ].mp4
</pre>

_[blank line]_

Additional notes:  
Notes such as config settings that may be helpful.

**Comment by JackDandy** [comment] 2017-01-06 19:01
>  I am unable to reproduce the issue 

then how will you be able to confirm a fix is correct ?

**Comment by JackDandy** [comment] 2017-01-06 19:43
>  I am unable to reproduce the issue 

then how will you be able to confirm a fix is correct ? 

I am unable to verify your findings, more info is needed.

What version of Kodi is this?

Closing this issue, by all means continue to reply in here if you have additional detail that can help replicate the issue.

**Closed by JackDandy** 2017-01-06 19:43 UTC

**Comment by dirkblaster** [comment] 2017-01-07 02:59
Sorry, I know this is a pain without steps to reproduce, but wanted to log it anyway in case someone else had seen a similar issue. The two systems have been working fine with each other for months without problems, but this is the first time I've seen this particular format of file be grabbed and thought perhaps the extra brackets/characters may have caused an exception or premature escape within a string command.

I've at least managed to salvage Kodi by wiping the entire video library database file under %appdata%/kodi/userdata

**Comment by JackDandy** [comment] 2017-01-07 03:30
It's no problem (read:pain), however, it **is** impossible to fix something that cannot be seen. 

FYI, in response to this thread, the filename format you reported was tested and proved totally fine.  As was reported, the filename is not sent to Kodi and therefore, this can not be the cause of Kodi going wonky. Kodi is told which title to update, it has a library path, so it goes to check that path for new files. Now, why your Kodo had bad data - is another question. All of this is why this issue is marked invalid. Basically, unless proven otherwise, you can be confident that there is no issue with SG notifying Kodi. However, I can only conclude that something, somehow made Kodi barf - so perhaps try to load the Kodi DB and examine filepaths therein and look for anomalies - if you can.

Good luck.
